# Generated by Django 2.1.7 on 2019-03-19 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=512, verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_on',
            field=models.DateField(blank=True, null=True, verbose_name='Due by'),
        ),
        migrations.AlterField(
            model_name='task',
            name='show_on',
            field=models.DateField(blank=True, null=True, verbose_name='Hide until'),
        ),
        migrations.AddField(
            model_name='note',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.Task'),
        ),
    ]
