# Generated by Django 2.1.7 on 2019-03-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190319_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
                ('tasks', models.ManyToManyField(related_name='tags', to='core.Task')),
            ],
        ),
    ]
