# Generated by Django 2.1.7 on 2019-04-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_token',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(help_text='Tag text (must be lowercase)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='show_on',
            field=models.DateField(blank=True, help_text='This task will not be shown under current tasks until this date.', null=True, verbose_name='Hide until'),
        ),
    ]
